services:
  - type: web
    name: djasoft
    env: php
    plan: free
    buildCommand: "composer install"
    startCommand: "php artisan serve --host=0.0.0.0 --port=10000"
    envVars:
      APP_ENV: production
      APP_KEY: base64:Jy0MGZKg9tDvOKMMWmBDB8t3NbdRizuGiRfD2kiagiQ=
      DB_CONNECTION: mysql
      DB_HOST: tu-host-db
      DB_PORT: 3306
      DB_DATABASE: tu-nombre-db
      DB_USERNAME: tu-usuario-db
      DB_PASSWORD: tu-contraseña-db

  - type: worker
    name: djasoft-queue
    env: php
    plan: free
    startCommand: "php artisan queue:work"

  - type: worker
    name: djasoft-reverb
    env: php
    plan: free
    startCommand: "php artisan reverb:start"

  - type: worker
    name: djasoft-migrate
    env: php
    plan: free
    startCommand: "php artisan migrate"
